language: java
jdk: 
  - oraclejdk8
  - oraclejdk9
  - openjdk8

services:
  - docker

before_install:
  - docker pull mongo
  - docker run -d -p 127.0.0.1:27017:27017 --name beaverDB -d mongo:latest
script: 
  - mvn test -B
