FORMAT: 1A
HOST: http://localhost:8080/api/

# BeaverCoffee
Specification of the available routes of the BeaverCoffe data store.

# Group Orders
## Order [/orders/{id}]
+ Parameters
 - id: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string, required)

### View Order [GET]
Req 12, Fetches the data for order with the given id.
+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes(Order)

### Update Order [PUT]
Updates for orders not in process are allowed. 
+ Request (application/json)
  + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

    + Attributes(Order)

+ Response 204

### Remove Order [DELETE]
Req 3, Removal of orders not in process are allowed.
+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 204

## Orders [/orders{?employeeID,status,from,to}]
### Create Order [POST]
Add a new order to the database. Returns an orderID.
+ Request (application/json)
  + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

    + Attributes(Order)

+ Response 201 (application/json)
    + Attributes
        - id: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string)

### View Orders [GET]
Req 12, Fetch current orders not i process by default, may be queried by employee id and or status
+ Parameters
    - status: pending, inprocess, finished (enum, optional) - one of pending, inprocess, finished
    - employeeID: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string, optional)
    - from: `2018-04-27T20:06+02:00` (string, optional) - From time period
    - to: `2018-04-28T20:06+02:00` (string, optional) - To time period

+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes(array[Order])

# Group Products
## Products [/products]
### View Products [GET]
Returns all products for sale.
+ Response 200 (application/json)

    + Attributes(array[Product])

# Group Employees
## Employee [/employees/{id}]
+ Parameters
 - id: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string, required)

### View Employee [GET]
Returns information about an employee with the given id.
+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes(Employee)

### Update Employee [PUT]
Overwrites information about the employee with the given id.
+ Request (application/json)

    + Attributes(Employee)

+ Response 204

## Employee Reports [GET /employees/{id}/reports{?from,to}]
Req 13.5
+ Parameters
    - id: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string, required)
    - from: `2018-04-27T20:06+02:00` (string, optional) - From time period
    - to: `2018-04-28T20:06+02:00` (string, optional) - To time period

+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes
        - report : abmalmba


## Employees [/employees]
### Create Employee [POST]
Req 12
+ Request (application/json)
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

    + Attributes(BaseEmployee)

+ Response 201 (application/json)
 + Attributes
        - id: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string)

### View Employees [GET]
Returns a list with all employees.
+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes(array[Employee])


## Employee reports [GET /employees/listing/{storeid}]
13.6
+ Parameters
    - storeid: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string)

+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes
        - report: katastrof

# Group Customers
## Customers [/customers]
### Create Customer [POST]
Req 12, Req 5 Branch manager and regular employee may add a customer to the datbase on this url.
+ Request (application/json)
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

    + Attributes(BaseCustomer)

+ Response 201 (application/json)
     + Attributes
        - id: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string)

### View Customers [GET]
Returns a list of all coustomers.
+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes(array[Customer])

## Customer Reports [GET /customers/reports{?postalcode,occupation,from,to}]
+ Parameters
    - postalcode: 212 13 (string, optional)
    - occupation: youtube influencer (string, optional)
    - from: `2018-04-27T20:06+02:00` (string, optional) - From time period
    - to: `2018-04-28T20:06+02:00` (string, optional) - To time period

+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes

# Group Stores
## Stores [/stores]
### View Stores [GET]
Req 12
+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes(array[Store])

## Store [/stores/{id}]
+ Parameters
 - id: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string, required)

### View Store [GET]
Req 12
+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes(Store)

## Store stock [GET /stores/{id}/stock]
Returns the current stock for a  store
+ Parameters
 - id: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string, required)


+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes(array[StockExample])

## Store Report [GET /stores/{id}/reports{?from,to,productIDs}]
Req 13.1, 13.2
+ Parameters
    - id: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string, required)
    - from: `2018-04-27T20:06+02:00` (string, optional) - From time period
    - to: `2018-04-28T20:06+02:00` (string, optional) - To time period
    - productIDs: `12345678-3715-4f91-8b4f-c4f3342f5a83`, `12345678-3715-4f91-8b4f-c4f3342f5a83` (array, optional)
   

+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes
        - store data: blalba

## Stock Reports [GET /stores/{id}/stock/reports{?from,to,productIDs}]
Req 13.4
+ Parameters
    - id: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string, required)
    - from: `2018-04-27T20:06+02:00` (string, optional) - From time period
    - to: `2018-04-28T20:06+02:00` (string, optional) - To time period
    - productIDs: `12345678-3715-4f91-8b4f-c4f3342f5a83`, `12345678-3715-4f91-8b4f-c4f3342f5a83` (array, optional)

+ Request
    + Headers

                 Authorization: `12345678-3715-4f91-8b4f-c4f3342f5a83` - Token from auth route

+ Response 200 (application/json)

    + Attributes
        - store data: blalba

# Group Authorization
Req 12, Returns an array of roles and a token for auth in other routes
## Authenticate [POST /authorization]
+ Request (applcation/json)

    + Attributes
        - name: ABC123 (string, required)
        - password: 029352jojoj35123  (string, required) - Hashed password

+ Response 200 (application/json)

    + Attributes(Session)

# Data Structures

## Authentication
 - name: ABC123 (string, required)
 - password: 029352jojoj35123  (string, required) - Hashed password

## Session
 - include UUID
 - roles: Cashier, Store Manager, Branch Manager, Corporate Sales (array)

## Adress (object)
 - street: Gejiersgatan 10 (string, required)
 - zip: 215 12 (string, required)
 - city: Malmö (string, required)
 - country
  - include Country

## Mobilephone
 - mobile: `+4612738592`, `+4644434593` (array)

## Homephone
 - home: 0401315023, 040150532 (array)

## PhoneNumbers (object)
 - include Mobilephone
 - include Homephone

## Person (object)
 - first: Jens (string, required) - Given name
 - last: Conny (string, required) - Surname
 - SSN: 098745028374 (string, required) - Social security number
 - homeAdress (array[Adress])

## ClubMember
 - include UUID
 - include Person
 - occupation: Youtube Influencer (string)
 - cards (array[Card]) 

## Card
 - numOfPurchases: 10 
 - barcode:`12345678-3715-4f91-8b4f-c4f3342f5a83` (string, required) - UUID v4
 - validCountry
    - code: SE
    - name: Sverige

## BaseCustomer
 - clubmember
  - include ClubMember
   

## Customer
 - include UUID
 - include BaseCustomer
 

## EmploymentHistory
 - postion: Beanmaker (string)
 - start: 1526633863 (number) - Unix epoch timestamp
 - end: 1526633863 (number) - Unix epoch timestamp
 - type: Full (string) - Employment Type

## BaseEmployee
- details (object)
    - include Person
    - phoneNumbers(PhoneNumbers)
 - employmentHistory (array[EmploymentHistory])

## Employee
 - include UUID
 - include BaseEmployee
 - Comments (array[Comment])


## Comment (object)
 - include UUID
 - include: 1526633863 (number) - Unix epoch timestamp 
 - employer: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string, required) - UUID v4
 - comment: You're my favorite guy, pal! (string, required) - Maximum length 300 characters

## Store
 - include UUID
 - branchID: `99999998-3715-4f91-8b4f-c4f3342f5a83` (string, required) - UUID v4
 - adress
  - include Adress
 - orders: `12345678-3715-4f91-8b4f-c4f3342f5a83`, `12345678-3715-4f91-8b4f-c4f3342f5a89`  (array)
 - stock (array[StockExample])

## StockExample
 - productId: `78970117-3715-4f91-8b4f-c4f3342f5a83` - (string, required) - UUID v4
 - quantity: 20 (string, required) - ID of product is the key 

## Branch
  - include UUID
  - Stores (array[Store])

## Country
 - code: SE
 - currency: SEK
 - language: SV
 - name: Sverige

## BaseProduct
  - name: EN=Brewed Coffe, SV=Bryggkaffe (array, required)
  - type: Brewed
  - quantity: 1 (string)
  - price: US=100, SE=10 (array, required)

  
## Product (object)
  - include UUID
  - include BaseProduct

## Order (object)
 - include UUID
 - include TimeStamp
 - discount: `%10` (optional) - Req 4
 - customer
  - include Customer
 - include EmployeeUUID
 - storeID: `69999998-3715-4f91-8b4f-c4f3342f5a83` (string, required) - UUID v4
 - products (array[OrderdProducts])
 - status: pending, inprocess, finished (enum, required) - one of pending, inprocess, finished

## TimeStamp
 - timestamp: 1526633863 (number) - Unix epoch timestamp

## UUID
 - id: `78970117-3715-4f91-8b4f-c4f3342f5a83` (string, required) - UUID v4

## EmployeeUUID
 - EmployeeID: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string, required) - UUID v4

## OrderdProducts
 - quantity: 10 (string, required) 
 - productID: `12345678-3715-4f91-8b4f-c4f3342f5a83` (string, required) - UUID v4

## Date
 - date: `2018-04-27T20:06+02:00` (string, required) - ISO something date format